/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BrowseIndexRouteImport } from './routes/browse/index'
import { Route as AppsIndexRouteImport } from './routes/apps/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as WorkerProductsRouteImport } from './routes/worker/products'
import { Route as WorkerNotificationsRouteImport } from './routes/worker/notifications'
import { Route as WorkerDashboardRouteImport } from './routes/worker/dashboard'
import { Route as WorkerAppsRouteImport } from './routes/worker/apps'
import { Route as ProductsIdRouteImport } from './routes/products/$id'
import { Route as BrowseIdRouteImport } from './routes/browse/$id'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminReportsRouteImport } from './routes/admin/reports'
import { Route as AdminProfileRouteImport } from './routes/admin/profile'
import { Route as AdminNotificationsRouteImport } from './routes/admin/notifications'
import { Route as AdminGlobalTemplateRouteImport } from './routes/admin/global-template'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminActivityRouteImport } from './routes/admin/activity'
import { Route as AppsAppIdIndexRouteImport } from './routes/apps/$appId/index'
import { Route as AdminProductsIndexRouteImport } from './routes/admin/products/index'
import { Route as AdminAppsIndexRouteImport } from './routes/admin/apps/index'
import { Route as AppsAppIdAddProductRouteImport } from './routes/apps/$appId/add-product'
import { Route as AdminProductsIdRouteImport } from './routes/admin/products/$id'
import { Route as AdminAppsAppIdIndexRouteImport } from './routes/admin/apps/$appId/index'
import { Route as AdminAppsAppIdCustomFormRouteImport } from './routes/admin/apps/$appId/custom-form'
import { Route as AdminAppsAppIdCategoryCategoryIdFieldsRouteImport } from './routes/admin/apps/$appId/category/$categoryId/fields'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseIndexRoute = BrowseIndexRouteImport.update({
  id: '/browse/',
  path: '/browse/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsIndexRoute = AppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkerProductsRoute = WorkerProductsRouteImport.update({
  id: '/worker/products',
  path: '/worker/products',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkerNotificationsRoute = WorkerNotificationsRouteImport.update({
  id: '/worker/notifications',
  path: '/worker/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkerDashboardRoute = WorkerDashboardRouteImport.update({
  id: '/worker/dashboard',
  path: '/worker/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkerAppsRoute = WorkerAppsRouteImport.update({
  id: '/worker/apps',
  path: '/worker/apps',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIdRoute = ProductsIdRouteImport.update({
  id: '/products/$id',
  path: '/products/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseIdRoute = BrowseIdRouteImport.update({
  id: '/browse/$id',
  path: '/browse/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/admin/profile',
  path: '/admin/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/admin/notifications',
  path: '/admin/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminGlobalTemplateRoute = AdminGlobalTemplateRouteImport.update({
  id: '/admin/global-template',
  path: '/admin/global-template',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminActivityRoute = AdminActivityRouteImport.update({
  id: '/admin/activity',
  path: '/admin/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsAppIdIndexRoute = AppsAppIdIndexRouteImport.update({
  id: '/apps/$appId/',
  path: '/apps/$appId/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductsIndexRoute = AdminProductsIndexRouteImport.update({
  id: '/admin/products/',
  path: '/admin/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAppsIndexRoute = AdminAppsIndexRouteImport.update({
  id: '/admin/apps/',
  path: '/admin/apps/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsAppIdAddProductRoute = AppsAppIdAddProductRouteImport.update({
  id: '/apps/$appId/add-product',
  path: '/apps/$appId/add-product',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductsIdRoute = AdminProductsIdRouteImport.update({
  id: '/admin/products/$id',
  path: '/admin/products/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAppsAppIdIndexRoute = AdminAppsAppIdIndexRouteImport.update({
  id: '/admin/apps/$appId/',
  path: '/admin/apps/$appId/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAppsAppIdCustomFormRoute =
  AdminAppsAppIdCustomFormRouteImport.update({
    id: '/admin/apps/$appId/custom-form',
    path: '/admin/apps/$appId/custom-form',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminAppsAppIdCategoryCategoryIdFieldsRoute =
  AdminAppsAppIdCategoryCategoryIdFieldsRouteImport.update({
    id: '/admin/apps/$appId/category/$categoryId/fields',
    path: '/admin/apps/$appId/category/$categoryId/fields',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/wishlist': typeof WishlistRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/global-template': typeof AdminGlobalTemplateRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/users': typeof AdminUsersRoute
  '/browse/$id': typeof BrowseIdRoute
  '/products/$id': typeof ProductsIdRoute
  '/worker/apps': typeof WorkerAppsRoute
  '/worker/dashboard': typeof WorkerDashboardRoute
  '/worker/notifications': typeof WorkerNotificationsRoute
  '/worker/products': typeof WorkerProductsRoute
  '/admin/': typeof AdminIndexRoute
  '/apps/': typeof AppsIndexRoute
  '/browse/': typeof BrowseIndexRoute
  '/admin/products/$id': typeof AdminProductsIdRoute
  '/apps/$appId/add-product': typeof AppsAppIdAddProductRoute
  '/admin/apps/': typeof AdminAppsIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
  '/apps/$appId/': typeof AppsAppIdIndexRoute
  '/admin/apps/$appId/custom-form': typeof AdminAppsAppIdCustomFormRoute
  '/admin/apps/$appId/': typeof AdminAppsAppIdIndexRoute
  '/admin/apps/$appId/category/$categoryId/fields': typeof AdminAppsAppIdCategoryCategoryIdFieldsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/wishlist': typeof WishlistRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/global-template': typeof AdminGlobalTemplateRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/users': typeof AdminUsersRoute
  '/browse/$id': typeof BrowseIdRoute
  '/products/$id': typeof ProductsIdRoute
  '/worker/apps': typeof WorkerAppsRoute
  '/worker/dashboard': typeof WorkerDashboardRoute
  '/worker/notifications': typeof WorkerNotificationsRoute
  '/worker/products': typeof WorkerProductsRoute
  '/admin': typeof AdminIndexRoute
  '/apps': typeof AppsIndexRoute
  '/browse': typeof BrowseIndexRoute
  '/admin/products/$id': typeof AdminProductsIdRoute
  '/apps/$appId/add-product': typeof AppsAppIdAddProductRoute
  '/admin/apps': typeof AdminAppsIndexRoute
  '/admin/products': typeof AdminProductsIndexRoute
  '/apps/$appId': typeof AppsAppIdIndexRoute
  '/admin/apps/$appId/custom-form': typeof AdminAppsAppIdCustomFormRoute
  '/admin/apps/$appId': typeof AdminAppsAppIdIndexRoute
  '/admin/apps/$appId/category/$categoryId/fields': typeof AdminAppsAppIdCategoryCategoryIdFieldsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/wishlist': typeof WishlistRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/global-template': typeof AdminGlobalTemplateRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/users': typeof AdminUsersRoute
  '/browse/$id': typeof BrowseIdRoute
  '/products/$id': typeof ProductsIdRoute
  '/worker/apps': typeof WorkerAppsRoute
  '/worker/dashboard': typeof WorkerDashboardRoute
  '/worker/notifications': typeof WorkerNotificationsRoute
  '/worker/products': typeof WorkerProductsRoute
  '/admin/': typeof AdminIndexRoute
  '/apps/': typeof AppsIndexRoute
  '/browse/': typeof BrowseIndexRoute
  '/admin/products/$id': typeof AdminProductsIdRoute
  '/apps/$appId/add-product': typeof AppsAppIdAddProductRoute
  '/admin/apps/': typeof AdminAppsIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
  '/apps/$appId/': typeof AppsAppIdIndexRoute
  '/admin/apps/$appId/custom-form': typeof AdminAppsAppIdCustomFormRoute
  '/admin/apps/$appId/': typeof AdminAppsAppIdIndexRoute
  '/admin/apps/$appId/category/$categoryId/fields': typeof AdminAppsAppIdCategoryCategoryIdFieldsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/notifications'
    | '/profile'
    | '/sitemap.xml'
    | '/wishlist'
    | '/admin/activity'
    | '/admin/dashboard'
    | '/admin/global-template'
    | '/admin/notifications'
    | '/admin/profile'
    | '/admin/reports'
    | '/admin/users'
    | '/browse/$id'
    | '/products/$id'
    | '/worker/apps'
    | '/worker/dashboard'
    | '/worker/notifications'
    | '/worker/products'
    | '/admin/'
    | '/apps/'
    | '/browse/'
    | '/admin/products/$id'
    | '/apps/$appId/add-product'
    | '/admin/apps/'
    | '/admin/products/'
    | '/apps/$appId/'
    | '/admin/apps/$appId/custom-form'
    | '/admin/apps/$appId/'
    | '/admin/apps/$appId/category/$categoryId/fields'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/notifications'
    | '/profile'
    | '/sitemap.xml'
    | '/wishlist'
    | '/admin/activity'
    | '/admin/dashboard'
    | '/admin/global-template'
    | '/admin/notifications'
    | '/admin/profile'
    | '/admin/reports'
    | '/admin/users'
    | '/browse/$id'
    | '/products/$id'
    | '/worker/apps'
    | '/worker/dashboard'
    | '/worker/notifications'
    | '/worker/products'
    | '/admin'
    | '/apps'
    | '/browse'
    | '/admin/products/$id'
    | '/apps/$appId/add-product'
    | '/admin/apps'
    | '/admin/products'
    | '/apps/$appId'
    | '/admin/apps/$appId/custom-form'
    | '/admin/apps/$appId'
    | '/admin/apps/$appId/category/$categoryId/fields'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/notifications'
    | '/profile'
    | '/sitemap.xml'
    | '/wishlist'
    | '/admin/activity'
    | '/admin/dashboard'
    | '/admin/global-template'
    | '/admin/notifications'
    | '/admin/profile'
    | '/admin/reports'
    | '/admin/users'
    | '/browse/$id'
    | '/products/$id'
    | '/worker/apps'
    | '/worker/dashboard'
    | '/worker/notifications'
    | '/worker/products'
    | '/admin/'
    | '/apps/'
    | '/browse/'
    | '/admin/products/$id'
    | '/apps/$appId/add-product'
    | '/admin/apps/'
    | '/admin/products/'
    | '/apps/$appId/'
    | '/admin/apps/$appId/custom-form'
    | '/admin/apps/$appId/'
    | '/admin/apps/$appId/category/$categoryId/fields'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  NotificationsRoute: typeof NotificationsRoute
  ProfileRoute: typeof ProfileRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WishlistRoute: typeof WishlistRoute
  AdminActivityRoute: typeof AdminActivityRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminGlobalTemplateRoute: typeof AdminGlobalTemplateRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  BrowseIdRoute: typeof BrowseIdRoute
  ProductsIdRoute: typeof ProductsIdRoute
  WorkerAppsRoute: typeof WorkerAppsRoute
  WorkerDashboardRoute: typeof WorkerDashboardRoute
  WorkerNotificationsRoute: typeof WorkerNotificationsRoute
  WorkerProductsRoute: typeof WorkerProductsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AppsIndexRoute: typeof AppsIndexRoute
  BrowseIndexRoute: typeof BrowseIndexRoute
  AdminProductsIdRoute: typeof AdminProductsIdRoute
  AppsAppIdAddProductRoute: typeof AppsAppIdAddProductRoute
  AdminAppsIndexRoute: typeof AdminAppsIndexRoute
  AdminProductsIndexRoute: typeof AdminProductsIndexRoute
  AppsAppIdIndexRoute: typeof AppsAppIdIndexRoute
  AdminAppsAppIdCustomFormRoute: typeof AdminAppsAppIdCustomFormRoute
  AdminAppsAppIdIndexRoute: typeof AdminAppsAppIdIndexRoute
  AdminAppsAppIdCategoryCategoryIdFieldsRoute: typeof AdminAppsAppIdCategoryCategoryIdFieldsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse/': {
      id: '/browse/'
      path: '/browse'
      fullPath: '/browse/'
      preLoaderRoute: typeof BrowseIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/': {
      id: '/apps/'
      path: '/apps'
      fullPath: '/apps/'
      preLoaderRoute: typeof AppsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/worker/products': {
      id: '/worker/products'
      path: '/worker/products'
      fullPath: '/worker/products'
      preLoaderRoute: typeof WorkerProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/worker/notifications': {
      id: '/worker/notifications'
      path: '/worker/notifications'
      fullPath: '/worker/notifications'
      preLoaderRoute: typeof WorkerNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/worker/dashboard': {
      id: '/worker/dashboard'
      path: '/worker/dashboard'
      fullPath: '/worker/dashboard'
      preLoaderRoute: typeof WorkerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/worker/apps': {
      id: '/worker/apps'
      path: '/worker/apps'
      fullPath: '/worker/apps'
      preLoaderRoute: typeof WorkerAppsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$id': {
      id: '/products/$id'
      path: '/products/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof ProductsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse/$id': {
      id: '/browse/$id'
      path: '/browse/$id'
      fullPath: '/browse/$id'
      preLoaderRoute: typeof BrowseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/admin/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/admin/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/global-template': {
      id: '/admin/global-template'
      path: '/admin/global-template'
      fullPath: '/admin/global-template'
      preLoaderRoute: typeof AdminGlobalTemplateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/activity': {
      id: '/admin/activity'
      path: '/admin/activity'
      fullPath: '/admin/activity'
      preLoaderRoute: typeof AdminActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/$appId/': {
      id: '/apps/$appId/'
      path: '/apps/$appId'
      fullPath: '/apps/$appId/'
      preLoaderRoute: typeof AppsAppIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/products/': {
      id: '/admin/products/'
      path: '/admin/products'
      fullPath: '/admin/products/'
      preLoaderRoute: typeof AdminProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/apps/': {
      id: '/admin/apps/'
      path: '/admin/apps'
      fullPath: '/admin/apps/'
      preLoaderRoute: typeof AdminAppsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/$appId/add-product': {
      id: '/apps/$appId/add-product'
      path: '/apps/$appId/add-product'
      fullPath: '/apps/$appId/add-product'
      preLoaderRoute: typeof AppsAppIdAddProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/products/$id': {
      id: '/admin/products/$id'
      path: '/admin/products/$id'
      fullPath: '/admin/products/$id'
      preLoaderRoute: typeof AdminProductsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/apps/$appId/': {
      id: '/admin/apps/$appId/'
      path: '/admin/apps/$appId'
      fullPath: '/admin/apps/$appId/'
      preLoaderRoute: typeof AdminAppsAppIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/apps/$appId/custom-form': {
      id: '/admin/apps/$appId/custom-form'
      path: '/admin/apps/$appId/custom-form'
      fullPath: '/admin/apps/$appId/custom-form'
      preLoaderRoute: typeof AdminAppsAppIdCustomFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/apps/$appId/category/$categoryId/fields': {
      id: '/admin/apps/$appId/category/$categoryId/fields'
      path: '/admin/apps/$appId/category/$categoryId/fields'
      fullPath: '/admin/apps/$appId/category/$categoryId/fields'
      preLoaderRoute: typeof AdminAppsAppIdCategoryCategoryIdFieldsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  NotificationsRoute: NotificationsRoute,
  ProfileRoute: ProfileRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WishlistRoute: WishlistRoute,
  AdminActivityRoute: AdminActivityRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminGlobalTemplateRoute: AdminGlobalTemplateRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminUsersRoute: AdminUsersRoute,
  BrowseIdRoute: BrowseIdRoute,
  ProductsIdRoute: ProductsIdRoute,
  WorkerAppsRoute: WorkerAppsRoute,
  WorkerDashboardRoute: WorkerDashboardRoute,
  WorkerNotificationsRoute: WorkerNotificationsRoute,
  WorkerProductsRoute: WorkerProductsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AppsIndexRoute: AppsIndexRoute,
  BrowseIndexRoute: BrowseIndexRoute,
  AdminProductsIdRoute: AdminProductsIdRoute,
  AppsAppIdAddProductRoute: AppsAppIdAddProductRoute,
  AdminAppsIndexRoute: AdminAppsIndexRoute,
  AdminProductsIndexRoute: AdminProductsIndexRoute,
  AppsAppIdIndexRoute: AppsAppIdIndexRoute,
  AdminAppsAppIdCustomFormRoute: AdminAppsAppIdCustomFormRoute,
  AdminAppsAppIdIndexRoute: AdminAppsAppIdIndexRoute,
  AdminAppsAppIdCategoryCategoryIdFieldsRoute:
    AdminAppsAppIdCategoryCategoryIdFieldsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
